FROM python:3.10-slim

# Install common dependencies
WORKDIR /app

# Build source code
COPY backend-websocket/* /app/
# 安装requirements.txt中指定的所有依赖
#RUN python3 -m pip install --no-cache-dir -r requirements.txt
RUN pip install websockets requests

# 运行Tornado web服务器
CMD ["python", "run.py", "-p", "9593"]
